// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsRXoy0lW27eX1jO_g8q72qIfYe8rkGCg',
    appId: '1:114152481636:android:a7c7873e8ca37f07a6d071',
    messagingSenderId: '114152481636',
    projectId: 'vistacall-83230',
    storageBucket: 'vistacall-83230.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiznEBhFUcnEJ0oxnfYCIp5dn93Rp9vzI',
    appId: '1:114152481636:ios:4b75a78fcb0c9b25a6d071',
    messagingSenderId: '114152481636',
    projectId: 'vistacall-83230',
    storageBucket: 'vistacall-83230.firebasestorage.app',
    androidClientId:
        '114152481636-rompgn3ek0tbj85qmbnumsi3m2mpd272.apps.googleusercontent.com',
    iosClientId:
        '114152481636-8ajti04ted8r0qknpslat1dn09dcvcqg.apps.googleusercontent.com',
    iosBundleId: 'com.example.vistaCallDoctor',
  );
}
